# Generated by Django 5.0 on 2024-02-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/profile/user_pic_default.svg', upload_to='profile'),
        ),
    ]
