# Generated by Django 5.0 on 2024-02-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_info', to='training.trainingday')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=256)),
                ('training_info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training', to='training.traininginfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trainingday',
            name='training_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_day', to='training.trainingpage'),
        ),
        migrations.CreateModel(
            name='TrainingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reps', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('training_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_stats', to='training.traininginfo')),
            ],
        ),
    ]
