# Generated by Django 5.0 on 2024-02-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingstats',
            name='training_data',
        ),
        migrations.RemoveField(
            model_name='trainingday',
            name='training',
        ),
        migrations.RemoveField(
            model_name='trainingstats',
            name='training',
        ),
        migrations.AddField(
            model_name='trainingstats',
            name='reps',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingstats',
            name='sets',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingstats',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='training_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_page', to='training.trainingpage'),
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_stats', to='training.trainingstats')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_info', to='training.training')),
                ('workout_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_info', to='training.trainingday')),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
