# Generated by Django 5.0 on 2024-02-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_trainingstats_training_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingday',
            name='training_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_day', to='training.trainingpage'),
        ),
    ]
