# Generated by Django 5.0 on 2024-02-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_training_training_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_info',
        ),
        migrations.AddField(
            model_name='traininginfo',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_info', to='training.training'),
            preserve_default=False,
        ),
    ]
