# Generated by Django 5.0 on 2024-01-31 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingday_training_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='training',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight',
        ),
        migrations.CreateModel(
            name='TrainingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_stats', to='training.training')),
            ],
        ),
    ]
