# Generated by Django 5.0 on 2024-02-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingday_training_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininginfo',
            name='workout_info',
        ),
        migrations.AddField(
            model_name='traininginfo',
            name='training_day',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='training.trainingday'),
            preserve_default=False,
        ),
    ]
