# Generated by Django 5.0 on 2024-02-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_traininginfo_workout_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginfo',
            name='training',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_info', to='training.training'),
        ),
    ]
