# Generated by Django 5.0 on 2024-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_trainingday_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingday',
            name='training',
        ),
        migrations.AddField(
            model_name='training',
            name='training_days',
            field=models.ManyToManyField(to='training.trainingday'),
        ),
        migrations.AddField(
            model_name='trainingday',
            name='day',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
