# Generated by Django 5.0 on 2024-01-31 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_trainingday_training_training_training_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_days',
            new_name='days',
        ),
    ]
