# Generated by Django 5.0 on 2024-02-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_traininginfo_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginfo',
            name='training_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_info', to='training.trainingday'),
        ),
    ]
