# Generated by Django 5.0 on 2024-01-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_rename_training_days_training_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='days',
        ),
        migrations.RemoveField(
            model_name='trainingday',
            name='day',
        ),
        migrations.AddField(
            model_name='trainingday',
            name='training',
            field=models.ManyToManyField(to='training.training'),
        ),
    ]
