# Generated by Django 5.0 on 2024-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_traininginfo_training_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstats',
            name='reps',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingstats',
            name='sets',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingstats',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
