# Generated by Django 5.0 on 2024-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_trainingstats_reps_alter_trainingstats_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstats',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
