# Generated by Django 5.0 on 2024-02-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AddField(
            model_name='meal',
            name='mealplan_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='mealplan.mealplanpage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('day', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='mealplan.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='MealPlanDay',
        ),
    ]
