# Generated by Django 5.0 on 2024-02-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0002_alter_meal_day_remove_meal_name_meal_mealplan_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='day',
            new_name='name',
        ),
    ]
