# Generated by Django 5.0 on 2024-02-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0005_alter_food_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='mealplan.meal'),
        ),
    ]
