# Generated by Django 5.0 on 2024-02-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0007_alter_food_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='day',
        ),
        migrations.CreateModel(
            name='MealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_info', to='mealplan.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_info', to='mealplan.meal')),
            ],
        ),
    ]
