# Generated by Django 5.0 on 2023-12-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_is_coach_alter_profile_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
