# Generated by Django 5.0 on 2023-12-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homepagearticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageArticle',
        ),
    ]
