# Generated by Django 5.0 on 2024-01-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
