# Generated by Django 5.0 on 2024-01-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_homepagearticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageArticle',
        ),
    ]
