# Generated by Django 5.0 on 2024-01-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chronic_illness',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_food',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='food_allergies',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Passive')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='muscles',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.TextField(default='no', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='spine',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='test_results',
            field=models.TextField(default='no', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='unfavourite_food',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
